### ISSUE TITLE
PKCS#11 Support for Encrypted Container Images

### ISSUE THREAD

**Issue by lumjjb** [containers/ocicrypt#20]
This thread contains discussion and implementation/design direction for PKCS#11 support for ocicrypt. This was started from https://github.com/containers/ocicrypt/pull/18  created by @Gsealy, and initial discussions from @stefanberger @jejb @jamjoom @lumjjb
 
The overall plan is to have the feature be experimental, and be formed based on usecases and features requested through discussions of the community. Once it is reached a more stable state, it will become part of the spec. Until then, it is not an officially supported protocol.
 
Below are some points from discussions within the PRs + side conversations.
 
**Initial experimental prototype**
- Based on https://github.com/containers/ocicrypt/pull/18 contribution
- Marked as experimental `org.opencontainers.image.enc.keys.experimental.pkcs11`
- Support EncryptWith and DecryptWith settings providing module path, PIN and socket number
- Support EncryptWith that takes in a public key
- Custom packet format for encrypted material attached to image annotations
 
**Experimental prototype iteration**
- Allow `EncryptWith` and `DecryptWith` passing a PKCS11 URI, this will provide
  - More universal resolution of keys
  - Ability to specify parameters
  - Ability to use remote HSMs
- Define information passed in encrypted packet metadata vs taken as `DecryptConfig` and the role of consumers
 
**More iterations including other features as asks/discussion create**
 
**Future:**
- The encrypted packet format should be secure and standardized backed by PKCS11
- Upgrade to OCI general use

**Comment by stefanberger** [comment]
I sent a PR today (#19 ) that does the following:

- Extends the existing function for parsing public keys with parsing a pkcs11 URI as a public key and returns a pkcs11uri object for it
- Extends the existing function for parsing a private key file content that describes the private key in form of yaml; the actual key is also described as a pkcs11 URI; the function then returns a pkcs11uri object for the private key
- Implements a function to parse a pkcs11 config file that is needed for declaring the paths where pkcs11 modules are to be found on a distro; it also allows to restrict the modules that can be used; the entries found in the config file are used as parameters to a pkcs11uri object; the assumption is that pkcs11 URIs can use `module-name=softhsm2` to describe /path/to/libsofthsm2.so since this would allow for system-independent support for picking a client shared library (as described in RFC 7512)
- Adds a low level Encrypt function that supports OAEP encryption using pkcs11 URI objects and *rsa.PublicKey objects (multiple recipients); it generates a JSON object with the encrypted blob base 64 encoded and embedded in a pre-recipient entry
- Adds a low level Decrypt function that supports decryption using pkcs11 URI objects describing private keys; all keys will be tried with all entries found in the given JSON and once a decryption succeeds, the plaintext is returned
- Adds test cases for setting up a SoftHSM2 (starting with Ubuntu Bionic, SoftHSM 2.2) covering the Encrypt and Decrypt function as well as parsing of private key files (yaml format) and pkcs11 config files influencing the module search behavior of the pkcs11uri library objects

I do NOT think that the encrypted packet format (the JSON it creates) will be backed by PKCS11 but this would have to be our extension.

My suggestion is to base the higher level code, such as that from #18 on top of #19 or modify it so that it does. 

As the commit message there states, parts of the code was reused from @Gsealy.

In the future we will likely need to extend the code there to support pkcs11 libraries for HSM devices for example that may not have the same restrictions as SoftHSM does, such as OAEP with SHA1 hash algorithm only. We may need to extend it with listing features the device supports and picking the best one, possibly writing the parameters 'somewhere' in case the Decrypt function needs them...

**Comment by stefanberger** [comment]
Can close this (for now)?
